spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.LastBite: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
