-- LastBite initial schema placeholder
-- Add your tables here

-- Example:
-- CREATE TABLE IF NOT EXISTS users (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     email VARCHAR(255) UNIQUE NOT NULL,
--     password_hash VARCHAR(255) NOT NULL,
--     full_name VARCHAR(255) NOT NULL,
--     phone VARCHAR(20),
--     role VARCHAR(50) NOT NULL DEFAULT 'CUSTOMER',
--     status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );
